export function normalizeText(text) {
  return String(text || "")
    .trim()
    .toLowerCase()
    .normalize("NFKC")
    .replace(/잘돗/g, "잘못")
    .replace(/쥬스/g, "주스")
    .replace(/앤드밀/g, "엔드밀")
    .replace(/이에요/g, "예요")
    .replace(/에요/g, "예요")
    .replace(/예여/g, "예요")
    .replace(/해주세여/g, "해주세요")
    .replace(/먹으로/g, "먹으러")
    .replace(/밥먹으로/g, "밥먹으러")
    .replace(/배가\s*고파요/g, "배고프다")
    .replace(/배가\s*고파/g, "배고프다")
    .replace(/배고파요/g, "배고프다")
    .replace(/배고파/g, "배고프다")
    .replace(/시장해요/g, "배고프다")
    .replace(/시장해/g, "배고프다")
    .replace(/안되요/g, "안 돼요")
    .replace(/안되냐/g, "안 되냐")
    .replace(/안되네/g, "안 되네")
    .replace(/카드키안돼요/g, "카드키가 안 돼요")
    .replace(/카드키안되요/g, "카드키가 안 돼요")
    .replace(/냉장고안돼요/g, "냉장고가 안 돼요")
    .replace(/냉장고안되요/g, "냉장고가 안 돼요")
    .replace(/얼음좀주세요/g, "얼음 주세요")
    .replace(/얼음주세요/g, "얼음 주세요")
    .replace(/문제있습니다/g, "문제가 있어요")
    .replace(/문제있어요/g, "문제가 있어요")
    .replace(/문제있어/g, "문제가 있어요")
    .replace(/잘못되었어요/g, "잘못")
    .replace(/잘못됐어요/g, "잘못")
    .replace(/잘못되었습니다/g, "잘못")
    .replace(/잘못됐습니다/g, "잘못")
    .replace(/잘못되었어/g, "잘못")
    .replace(/잘못됐어/g, "잘못")
    .replace(/잘못된거예요/g, "잘못")
    .replace(/잘못된거야/g, "잘못")
    .replace(/잘못된 거예요/g, "잘못")
    .replace(/잘못된 거야/g, "잘못")
    .replace(/틀렸어요/g, "틀리다")
    .replace(/틀렸습니다/g, "틀리다")
    .replace(/틀렸어/g, "틀리다")
    .replace(/틀린거예요/g, "틀리다")
    .replace(/틀린거야/g, "틀리다")
    .replace(/틀린 거예요/g, "틀리다")
    .replace(/틀린 거야/g, "틀리다")
    .replace(/모릅니다/g, "모르다")
    .replace(/모른다/g, "모르다")
    .replace(/모르겠어요/g, "모르다")
    .replace(/모르겠어/g, "모르다")
    .replace(/건강해요/g, "건강하다")
    .replace(/건강해/g, "건강하다")
    .replace(/건강합니다/g, "건강하다")
    .replace(/건강한상태/g, "건강하다")
    .replace(/옴기/g, "옮기")
    .replace(/옴겨/g, "옮겨")
    .replace(/나눠주세여/g, "나누다")
    .replace(/나눠주세요/g, "나누다")
    .replace(/나눠줘요/g, "나누다")
    .replace(/나눠줘/g, "나누다")
    .replace(/나누어주다/g, "나누다")
    .replace(/나눠주다/g, "나누다")
    .replace(/배분해요/g, "나누다")
    .replace(/배분해/g, "나누다")
    .replace(/분배해요/g, "나누다")
    .replace(/분배해/g, "나누다")
    .replace(/옮겨주세여/g, "옮기다")
    .replace(/옮겨주세요/g, "옮기다")
    .replace(/옮겨줘요/g, "옮기다")
    .replace(/옮겨줘/g, "옮기다")
    .replace(/옮겨주다/g, "옮기다")
    .replace(/옮겨요/g, "옮기다")
    .replace(/(^|\s)옮겨(?=$|\s)/g, "$1옮기다")
    .replace(/잘몰라요/g, "모르다")
    .replace(/잘 몰라요/g, "모르다")
    .replace(/잘몰라/g, "모르다")
    .replace(/잘 몰라/g, "모르다")
    .replace(/몰라요/g, "모르다")
    .replace(/(^|\s)몰라(?=$|\s)/g, "$1모르다")
    .replace(/이쁘/g, "예쁘")
    .replace(/깍/g, "깎")
    .replace(/더워요/g, "덥다")
    .replace(/더워/g, "덥다")
    .replace(/한가해요/g, "한가하다")
    .replace(/한가해/g, "한가하다")
    .replace(/잘하고있어요/g, "잘하다")
    .replace(/잘하고있어/g, "잘하다")
    .replace(/잘하고있네/g, "잘하다")
    .replace(/잘 하고 있어요/g, "잘하다")
    .replace(/잘 하고 있어/g, "잘하다")
    .replace(/예뻐요/g, "예쁘다")
    .replace(/예뻐/g, "예쁘다")
    .replace(/이쁘다/g, "예쁘다")
    .replace(/이뻐요/g, "예쁘다")
    .replace(/이뻐/g, "예쁘다")
    .replace(/귀여워요/g, "귀엽다")
    .replace(/귀여워/g, "귀엽다")
    .replace(/멋있어요/g, "멋있다")
    .replace(/멋있어/g, "멋있다")
    .replace(/괜찮아요/g, "괜찮다")
    .replace(/괜찮아/g, "괜찮다")
    .replace(/배불러요/g, "배부르다")
    .replace(/배불러/g, "배부르다")
    .replace(/졸려요/g, "졸리다")
    .replace(/졸려/g, "졸리다")
    .replace(/힘들어요/g, "힘들다")
    .replace(/힘들어/g, "힘들다")
    .replace(/무거워요/g, "무겁다")
    .replace(/무거워/g, "무겁다")
    .replace(/가벼워요/g, "가볍다")
    .replace(/가벼워/g, "가볍다")
    .replace(/비싸요/g, "비싸다")
    .replace(/(^|\\s)비싸(?=$|\\s)/g, "$1비싸다")
    .replace(/(^|\\s)싸요(?=$|\\s)/g, "$1싸다")
    .replace(/뜨거워요/g, "뜨겁다")
    .replace(/뜨거워/g, "뜨겁다")
    .replace(/차가워요/g, "차갑다")
    .replace(/차가워/g, "차갑다")
    .replace(/안전해요/g, "안전하다")
    .replace(/안전해/g, "안전하다")
    .replace(/위험해요/g, "위험하다")
    .replace(/위험해/g, "위험하다")
    .replace(/잘생겼어요/g, "잘생겼다")
    .replace(/잘생겼어/g, "잘생겼다")
    .replace(/깎아줘요/g, "깎다")
    .replace(/깎아줘/g, "깎다")
    .replace(/깍아줘요/g, "깎다")
    .replace(/깍아줘/g, "깎다")
    .replace(/완성됐어요/g, "완성")
    .replace(/완성됐어/g, "완성")
    .replace(/완성됐네/g, "완성")
    .replace(/완료됐어요/g, "완성")
    .replace(/완료됐어/g, "완성")
    .replace(/거의 다 됐어요/g, "완성")
    .replace(/거의 다 됐어/g, "완성")
    .replace(/거의다됐어요/g, "완성")
    .replace(/거의다됐어/g, "완성")
    .replace(/큰일났어요/g, "큰일이다")
    .replace(/큰일났어/g, "큰일이다")
    .replace(/큰일났네/g, "큰일이다")
    .replace(/큰일난다/g, "큰일이다")
    .replace(/줄었어요/g, "줄다")
    .replace(/줄었다/g, "줄다")
    .replace(/바빠요/g, "바쁘다")
    .replace(/바빠/g, "바쁘다")
    .replace(/시원해요/g, "시원하다")
    .replace(/시원해/g, "시원하다")
    .replace(/심각해요/g, "심각하다")
    .replace(/심각해/g, "심각하다")
    .replace(/좋아요/g, "좋다")
    .replace(/나빠요/g, "나쁘다")
    .replace(/나빠/g, "나쁘다")
    .replace(/편해요/g, "편하다")
    .replace(/편해/g, "편하다")
    .replace(/불편해요/g, "불편하다")
    .replace(/불편해/g, "불편하다")
    .replace(/넓어요/g, "넓다")
    .replace(/넓어/g, "넓다")
    .replace(/좁아요/g, "좁다")
    .replace(/좁아/g, "좁다")
    .replace(/멀어요/g, "멀다")
    .replace(/멀어/g, "멀다")
    .replace(/가까워요/g, "가깝다")
    .replace(/가까워/g, "가깝다")
    .replace(/빨라요/g, "빠르다")
    .replace(/빨라/g, "빠르다")
    .replace(/느려요/g, "느리다")
    .replace(/느려/g, "느리다")
    .replace(/시끄러워요/g, "시끄럽다")
    .replace(/시끄러워/g, "시끄럽다")
    .replace(/조용해요/g, "조용하다")
    .replace(/조용해/g, "조용하다")
    .replace(/더러워요/g, "더럽다")
    .replace(/더러워/g, "더럽다")
    .replace(/냄새나요/g, "냄새")
    .replace(/냄새나/g, "냄새")
    .replace(/뭐에요/g, "뭐예요")
    .replace(/[“”"'`’]/g, "")
    .replace(/\s+/g, " ");
}

export function compactText(text) {
  return normalizeText(text).replace(/[^0-9a-zA-Z가-힣\u0E00-\u0E7F]+/g, "");
}

export function escapeHtml(text) {
  return String(text || "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}
